#############################################################################
# Makefile for building: pdfreader
# Generated by qmake (3.1) (Qt 5.12.9)
# Project:  pdfreader.pro
# Template: app
# Command: /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/qmake -o Makefile pdfreader.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../mylib/mupdf-1.12.0-source/include -I../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include -I../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets -I../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui -I../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore -I. -I../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pdfreader1.0.0
DISTDIR = /home/trgue/qt/pdfreader/.tmp/pdfreader1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/home/trgue/mylib/mupdf-1.12.0-source/build/release -lmupdf -lmuthreads -lmupdfthird /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/lib/libQt5Widgets.so /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/lib/libQt5Gui.so /home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/lib/libQt5Core.so -lpthread   
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_res.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_res.o \
		moc_mainwindow.o
DIST          = ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_pre.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/linux.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/sanitize.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base-unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-base.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/qconfig.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_functions.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_config.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exclusive_builds.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/toolchain.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_pre.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resolve_config.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_post.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/warn_on.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resources.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/moc.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/uic.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/unix/thread.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qmake_use.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/file_copies.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/testcase_targets.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exceptions.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/yacc.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/lex.prf \
		pdfreader.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = pdfreader
DESTDIR       = 
TARGET        = pdfreader


first: all
####### Build rules

pdfreader:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pdfreader.pro ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++/qmake.conf ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_pre.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/linux.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/sanitize.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base-unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-base.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-unix.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/qconfig.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_zlib_private.pri \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_functions.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_config.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exclusive_builds.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/toolchain.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_pre.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resolve_config.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_post.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/warn_on.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resources.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/moc.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/uic.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/unix/thread.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qmake_use.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/file_copies.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/testcase_targets.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exceptions.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/yacc.prf \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/lex.prf \
		pdfreader.pro \
		res.qrc
	$(QMAKE) -o Makefile pdfreader.pro
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_pre.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/unix.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/linux.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/sanitize.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/gcc-base-unix.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-base.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/common/g++-unix.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/qconfig.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_charts_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_core_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_edid_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_gui_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_input_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_network_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qml_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quick_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_service_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_sql_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_xml_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/modules/qt_lib_zlib_private.pri:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_functions.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt_config.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exclusive_builds.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/toolchain.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_pre.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resolve_config.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/default_post.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/warn_on.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qt.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/resources.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/moc.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/uic.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/unix/thread.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/qmake_use.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/file_copies.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/testcase_targets.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/exceptions.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/yacc.prf:
../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/lex.prf:
pdfreader.pro:
res.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile pdfreader.pro

qmake_all: FORCE


all: Makefile pdfreader

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/rcc \
		style.qss \
		up.png \
		down.png \
		down_clicked.png \
		up_clicked.png
	/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/data/dummy.cpp
	arm-linux-gnueabihf-g++ -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -O2 -march=armv7-a -mtune=cortex-a7 -mfpu=neon -mfloat-abi=hard -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QMainWindow \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qmainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtguiglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig-bootstrapped.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtcore-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsystemdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qprocessordetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcompilerdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtypeinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsysinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlogging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qflags.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbasicatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_bootstrap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qgenericatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_cxx11.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_msvc.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobalstatic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmutex.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnumeric.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qversiontagging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtgui-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgets-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnamespace.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs_win.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstring.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qchar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrefcount.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qarraydata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringliteral.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringbuilder.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiterator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhashfunctions.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpair.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearraylist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregexp.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringmatcher.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcoreevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qscopedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmetatype.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvarlengtharray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontainerfwd.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmargins.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpaintdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrect.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsize.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpoint.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpalette.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcolor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgb.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgba64.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qbrush.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvector.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qmatrix.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpolygon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qregion.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdatastream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiodevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qline.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtransform.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainterpath.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qimage.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixelformat.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qshareddata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhash.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfont.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontmetrics.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qsizepolicy.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcursor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qkeysequence.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvariant.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdebug.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtextstream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlocale.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qset.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontiguouscache.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurlquery.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfile.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfiledevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvector2d.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtouchdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qicon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qframe.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qabstractitemmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qitemselectionmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyleoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractspinbox.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvalidator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregularexpression.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyle.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabbar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qrubberband.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidgetItem \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScroller \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscroller.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QObject \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QPointF \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScrollerProperties \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollerproperties.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QScopedPointer \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QMetaType \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QVariant \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QPushButton \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qpushbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QImage \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QIcon \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QSize \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QPixmap \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QLabel \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlabel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsScene \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsscene.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpen.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsProxyWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsproxywidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicswidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicslayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsView \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainter.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtextoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QVBoxLayout \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qboxlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgridlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QHBoxLayout \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/version.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/config.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/system.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/memento.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/track-usage.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/context.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/geometry.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/getopt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/hash.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/string-util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pool.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/tree.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bidi.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/xml.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/stream.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compress.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compressed-buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/filter.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/store.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/archive.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/colorspace.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pixmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/separation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bitmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/image.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/shade.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/path.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/color-management.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/device.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/display-list.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/structured-text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/transition.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph-cache.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/link.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/outline.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/annotation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/band-writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pnm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-png.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pwg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pcl.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pclm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-ps.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-psd.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-svg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-tga.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/name-table.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/object.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/parse.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/xref.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/page.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/interpret.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/cmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/resource.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/annot.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/field.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/widget.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/appearance.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/event.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/javascript.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/output-pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/clean.h \
		moc_predefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/moc
	/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/bin/moc $(DEFINES) --include /home/trgue/qt/pdfreader/moc_predefs.h -I/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/mkspecs/linux-arm-gnueabi-g++ -I/home/trgue/qt/pdfreader -I/home/trgue/mylib/mupdf-1.12.0-source/include -I/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include -I/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets -I/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui -I/home/trgue/qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/4.9.4 -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/4.9.4/arm-linux-gnueabihf -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include/c++/4.9.4/backward -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.9.4/include -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/lib/gcc/arm-linux-gnueabihf/4.9.4/include-fixed -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/include -I/usr/local/arm/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QMainWindow \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qmainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtguiglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig-bootstrapped.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtcore-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsystemdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qprocessordetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcompilerdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtypeinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsysinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlogging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qflags.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbasicatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_bootstrap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qgenericatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_cxx11.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_msvc.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobalstatic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmutex.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnumeric.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qversiontagging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtgui-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgets-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnamespace.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs_win.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstring.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qchar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrefcount.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qarraydata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringliteral.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringbuilder.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiterator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhashfunctions.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpair.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearraylist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregexp.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringmatcher.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcoreevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qscopedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmetatype.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvarlengtharray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontainerfwd.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmargins.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpaintdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrect.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsize.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpoint.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpalette.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcolor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgb.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgba64.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qbrush.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvector.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qmatrix.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpolygon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qregion.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdatastream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiodevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qline.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtransform.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainterpath.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qimage.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixelformat.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qshareddata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhash.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfont.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontmetrics.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qsizepolicy.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcursor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qkeysequence.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvariant.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdebug.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtextstream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlocale.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qset.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontiguouscache.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurlquery.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfile.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfiledevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvector2d.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtouchdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qicon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qframe.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qabstractitemmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qitemselectionmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyleoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractspinbox.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvalidator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregularexpression.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyle.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabbar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qrubberband.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidgetItem \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScroller \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscroller.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QObject \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QPointF \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScrollerProperties \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollerproperties.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QScopedPointer \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QMetaType \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QVariant \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QPushButton \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qpushbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QImage \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QIcon \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QSize \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QPixmap \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QLabel \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlabel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsScene \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsscene.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpen.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsProxyWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsproxywidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicswidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicslayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsView \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainter.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtextoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QVBoxLayout \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qboxlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgridlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QHBoxLayout \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/version.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/config.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/system.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/memento.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/track-usage.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/context.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/geometry.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/getopt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/hash.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/string-util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pool.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/tree.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bidi.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/xml.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/stream.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compress.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compressed-buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/filter.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/store.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/archive.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/colorspace.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pixmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/separation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bitmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/image.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/shade.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/path.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/color-management.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/device.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/display-list.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/structured-text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/transition.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph-cache.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/link.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/outline.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/annotation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/band-writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pnm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-png.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pwg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pcl.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pclm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-ps.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-psd.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-svg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-tga.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/name-table.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/object.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/parse.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/xref.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/page.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/interpret.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/cmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/resource.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/annot.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/field.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/widget.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/appearance.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/event.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/javascript.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/output-pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/clean.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QApplication \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qapplication.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcoreapplication.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qeventloop.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qdesktopwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qguiapplication.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qinputmethod.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QMainWindow \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qmainwindow.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtguiglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobal.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig-bootstrapped.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qconfig.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtcore-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsystemdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qprocessordetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcompilerdetection.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtypeinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsysinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlogging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qflags.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbasicatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_bootstrap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qgenericatomic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_cxx11.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qatomic_msvc.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qglobalstatic.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmutex.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnumeric.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qversiontagging.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtgui-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtwidgets-config.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qnamespace.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobjectdefs_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qwindowdefs_win.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstring.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qchar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrefcount.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qarraydata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringliteral.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringbuilder.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qalgorithms.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiterator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhashfunctions.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpair.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qbytearraylist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringlist.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregexp.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qstringmatcher.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcoreevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qscopedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmetatype.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvarlengtharray.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontainerfwd.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qobject_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmargins.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpaintdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qrect.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsize.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qpoint.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpalette.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcolor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgb.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qrgba64.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qbrush.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvector.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qmatrix.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpolygon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qregion.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdatastream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qiodevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qline.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtransform.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainterpath.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qimage.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixelformat.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpixmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qshareddata.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qhash.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qsharedpointer_impl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfont.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontmetrics.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qfontinfo.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qsizepolicy.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qcursor.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qkeysequence.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qevent.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qvariant.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qmap.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qdebug.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qtextstream.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qlocale.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qset.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qcontiguouscache.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurl.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qurlquery.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfile.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qfiledevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvector2d.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtouchdevice.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qicon.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistwidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlistview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qframe.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qabstractitemmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qitemselectionmodel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyleoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractspinbox.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qvalidator.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/qregularexpression.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractslider.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qstyle.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qtabbar.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qrubberband.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QListWidgetItem \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScroller \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscroller.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QObject \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QPointF \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QScrollerProperties \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollerproperties.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QScopedPointer \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QMetaType \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QVariant \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QPushButton \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qpushbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qabstractbutton.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QImage \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QIcon \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QSize \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/QPixmap \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QLabel \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlabel.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsScene \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsscene.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpen.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsProxyWidget \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsproxywidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicswidget.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicslayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QGraphicsView \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgraphicsview.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qpainter.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtGui/qtextoption.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qscrollarea.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QVBoxLayout \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qboxlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qlayoutitem.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/qgridlayout.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtWidgets/QHBoxLayout \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/version.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/config.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/system.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/memento.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/track-usage.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/context.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/geometry.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/getopt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/hash.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/string-util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pool.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/tree.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bidi.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/xml.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/stream.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compress.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/compressed-buffer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/filter.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/store.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/archive.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/colorspace.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/pixmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/separation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/bitmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/image.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/shade.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/path.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/color-management.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/device.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/display-list.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/structured-text.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/transition.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/glyph-cache.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/link.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/outline.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/annotation.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/util.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/band-writer.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pnm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-png.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pwg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pcl.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-pclm.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-ps.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-psd.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-svg.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/fitz/output-tga.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/name-table.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/object.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/document.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/parse.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/xref.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/crypt.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/page.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/interpret.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/font.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/cmap.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/resource.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/annot.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/field.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/widget.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/appearance.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/event.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/javascript.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/output-pdf.h \
		../../mylib/mupdf-1.12.0-source/include/mupdf/pdf/clean.h \
		../../qt-everywhere/qt-everywhere-src-5.12.9/arm-qt/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/pdfreader/bin || mkdir -p $(INSTALL_ROOT)/opt/pdfreader/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/pdfreader/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/pdfreader/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/pdfreader/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/pdfreader/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

